-- hyprland.lua
-- Entry point. All configuration is split into modules.
-- Each require() is isolated -- an error in one won't break others.

hl.config({
  autogenerated = false,
  ["debug.enable_stdout_logs"] = true,
})

print("STDOUT TEST " .. os.date())

require("modules/theme")
require("modules/monitors")
require("modules/options")
require("modules/binds")
require("modules/rules")
require("modules/autostart")
