general {
  lock_cmd         = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd  = hyprctl dispatch dpms on
  inhibit_sleep    = 3
}

# --------------------------------------------------------
# BATTERY: dim @ 5m
# AC:      dim @ 14m
# --------------------------------------------------------
listener {
  timeout    = 300
  on-timeout = ~/.config/hypr/scripts/idle-action.sh "brightnessctl -s set 20%" "skip"
  on-resume  = ~/.config/hypr/scripts/idle-action.sh "brightnessctl -r" "skip"
}

listener {
  timeout    = 840
  on-timeout = ~/.config/hypr/scripts/idle-action.sh "skip" "brightnessctl -s set 20%"
  on-resume  = ~/.config/hypr/scripts/idle-action.sh "skip" "brightnessctl -r"
}

# --------------------------------------------------------
# BATTERY: lock @ 6m
# AC:      lock @ 15m
# --------------------------------------------------------
listener {
  timeout    = 360
  on-timeout = ~/.config/hypr/scripts/idle-action.sh "loginctl lock-session" "skip"
}

listener {
  timeout    = 900
  on-timeout = ~/.config/hypr/scripts/idle-action.sh "skip" "loginctl lock-session"
}

# --------------------------------------------------------
# BATTERY: dpms off @ 6m (same as lock, screen off immediately)
# AC:      dpms off @ 15m
# --------------------------------------------------------
listener {
  timeout    = 360
  on-timeout = ~/.config/hypr/scripts/idle-action.sh "hyprctl dispatch dpms off" "skip"
  on-resume  = ~/.config/hypr/scripts/idle-action.sh "hyprctl dispatch dpms on" "skip"
}

listener {
  timeout    = 900
  on-timeout = ~/.config/hypr/scripts/idle-action.sh "skip" "hyprctl dispatch dpms off"
  on-resume  = ~/.config/hypr/scripts/idle-action.sh "skip" "hyprctl dispatch dpms on"
}
