# New Hyprpaper Syntax
wallpaper {
    # Leave monitor blank to apply as a fallback to all monitors
    monitor = 
    path = $HOME/.config/hypr/wallpapers/wallpaper.png
    fit_mode = cover
}

# Misc settings stay outside the block
splash = false
ipc = true
